### ISSUE TITLE
Dodatkowe funkcje i poprawki

### ISSUE THREAD

**Issue by krzgr** [krzgr/Memory-slowne#2]
Kilka poprawek do obecnego stanu klasy __WordMemoryGame__:
1. funkcja __setNumberOfAnswears()__ jest niepotrzebna
2. zamiast __setNewPlayer()__ -> __addNewPlayer()__ oraz _return_  __self.savePlayerStatistics()__
3. __setNickname()__- oprócz ustawiania self.nickname ma za zadanie:
     - sprawdzić, czy dany nick istnieje w _self.players_dict_
     - jeżeli tak, to ustawia nick i zwraca wartość True 
     - jeżeli nie to ma dodać nowego gracza do tej bazy ( __addNewPlayer()__ ) i zwaraca wartość funkcji __addNewPlayer()__
4.  __getPlayerStatistics()__ do usunięcia
5. funkcja __shuffleWords()__ jest do poprawy
6. funkcja __setGameType()__ jest do usunięcia

Funkcje, których brakuje w tej klasie:
1. __getAllPlayersStatistics()__ <- zwraca listę krotek w postaci __[(nick, [statystyki]), (nick2, [statystyki2]), itd.]__ 
   nick <- string
   [statystyki2] <- czteroelementowa lista int'ów

**Comment by krzgr** [comment]
### Zmiana koncepcji!
funckcja __getPlayerStatistics()__ ma być usunięta

**Comment by koltonjakub** [comment]
dla celów optymalizacji można podzielić te funckje, jedna by tworzyła tą funckję jako atrybut klasy WordMemoryGame, druga by go tylko zwracała np:

getAllPlayersStatistics:
return self.playersStatsList

initSelfPlayersStatistics:
tutaj ciało funckji
