### ISSUE TITLE
Dodatkowe funkcje do klasy WordMemoryGame

### ISSUE THREAD

**Issue by krzgr** [krzgr/Memory-slowne#4]
Kilka dodatkowych funkcji:
1. _getNumberOfCorrectAnswers()_ <- _return self.numberOfCorrectAnswers_
2. _getNumberOfAllAnswers()_ <- _return self.numberOfAllAnswers_
3. _getDurationOfLookingAtCorrectAnswersAsSeconds()_ <- wzór: _5 * 2^(self.numberOfCorrectAnswers // 5)_
4. _addPlayerAnswer(word)_  <- dodaje do listy _self.playerSelectedWords_ słowo
5. _isGameFinished()_ 
6. _playerWin()_ <- sprawdza, czy słowa dodane gracza dodane poprzez funkcje _addPlayerAnswer()_ odpowiadają _self.correctAnswers_.        __Nie ważna kolejność!!__

Dodatkowo w tej klasie powinno pojawić się pole:  _self.playerSelectedWords_ <- lista zainicjalizowana jako pusta.
Oprócz tego każdorazowy zapis lub odczyt pliku ma mieć postać _open("ścieżka dostępu", "tryb otwarcia",_ __encoding="utf-8"__ _)_ <- __Bardzo ważne!__

Każdorazowe wywołanie funkcji _shuffleWords()_ jest równoznaczne z rozpoczęcie nowej rozgrywki.
- Jeżeli lista _self.playerSelectedWords_ jest pusta to liczba gier gracza nie ulega zmianie
- W przeciwnym razie traktujemy rozpoczętą gre jako przegraną 

Na końcu tej funkcji ustawiamy _self.playerSelectedWords_ = []

**Comment by koltonjakub** [comment]
czy funkcja addPlayerSelectedWords ma cokolwiek zwracać? na razie dodałem tam #return True, można to odkomentować, albo przerobić na wyjątek żeby zwracał False w razie błędu

**Comment by koltonjakub** [comment]
czy mamy już ustaloną kolejność, jeśli chodzi o to które liczby co oznaczają w 4-elementowej liście przypisywanej każdemu graczowi, jeśli tak to jaką. Zgadauje że jest zgodna z tymi wyświetlanymi w GUI, ale wolę się dopytać

**Comment by koltonjakub** [comment]
uznałem że (self.playersDict[self.nickname])[1] będzie ilością rozegranych gier, jeśli powinno być inaczej, daj znać zmienie to na poczekaniu, natomiast
(self.playersDict[self.nickname])[0] będzie ilością gier wygranych

**Comment by koltonjakub** [comment]
nie rozumiem dokładnie co ma robić funkcja start new game, dodałem w jej szkielecie self.shuffleWords(), jednak :
-sprawdzanie stanu gry: co ma dokładnie robić ta funkcja
- jakie dokładnie statystyki mają być dodane do pól graczy

**Comment by krzgr** [comment]
> czy funkcja addPlayerSelectedWords ma cokolwiek zwracać? na razie dodałem tam #return True, można to odkomentować, albo przerobić na wyjątek żeby zwracał False w razie błędu

Nie ma nic zwracać


> nie rozumiem dokładnie co ma robić funkcja start new game, dodałem w jej szkielecie self.shuffleWords(), jednak : -sprawdzanie stanu gry: co ma dokładnie robić ta funkcja
> 
> * jakie dokładnie statystyki mają być dodane do pól graczy

Funkcja _startNewGame()_ nie ma istnieć w tej klasie (mój błąd podczas pisania listy).

**Comment by krzgr** [comment]
> uznałem że (self.playersDict[self.nickname])[1] będzie ilością rozegranych gier, jeśli powinno być inaczej, daj znać zmienie to na poczekaniu, natomiast (self.playersDict[self.nickname])[0] będzie ilością gier wygranych

Co oznaczają teraz poszczególne liczy w _self.playersDict_ ?

**Comment by koltonjakub** [comment]
Kolejne elementy lisy self.playersDict: [ ilość wygranych, ilość wszystkich gier, ilość poprawnych, ilość wszystkich odpowiedzi ]
