### ISSUE TITLE
Treść maila i sprawozdanie NPG

### ISSUE THREAD

**Issue by krzgr** [krzgr/Memory-slowne#5]
Temat maila: [NPG_2022_PROJEKT]
Numer zespołu : temat projektu
1. Imię i nazwisko pierwszego członka zespołu 
2. Imię i nazwisko drugiego członka zespołu 
3. Imię i nazwisko trzeciego członka zespołu

Link do repozytorium
[Plik z sprawozdaniem]

**Comment by koltonjakub** [comment]
Plik ze sprawozdaniem:

Każdy podpunkt ma mieć postać:
-opis danej funkcjonalności programu
-screenshot z programu
-autor funkcjonalności
-data wykonania funkcjonalności
